const CSIT_CARDS=[
{front:"What are four common paths into an IT career?",back:"Certifications, formal education, internships, and jobs or work experience."},
{front:"What major hardware does Module 1 introduce?",back:"Cases, motherboards, power supplies, CPUs, RAM, expansion cards, storage, connectors, ports, and cables."},
{front:"What does ESD stand for?",back:"Electrostatic Discharge—static electricity moving between differently charged surfaces."},
{front:"How little ESD voltage can damage a computer component?",back:"Less than 30 volts."},
{front:"About how many volts of static electricity can a person first feel?",back:"About 3,000 volts."},
{front:"A painful or noisy static shock may exceed what voltage?",back:"10,000 volts."},
{front:"What is self-grounding?",back:"Touching a grounded object before electronic equipment to discharge static electricity."},
{front:"Name four ways to prevent ESD.",back:"Antistatic bags, grounded workbench mats, grounded floor mats, and antistatic wrist straps."},
{front:"Why must electrical equipment be grounded?",back:"It gives fault current a low-resistance path away from the equipment."},
{front:"Why can printer power supplies remain hazardous after shutdown?",back:"Some components retain high voltage even after the device is turned off."},
{front:"Why should you not use a random AC adapter?",back:"Adapters are device-specific; an incompatible one can damage both the adapter and device."},
{front:"What electrical conversion does a computer power supply perform?",back:"It converts wall-outlet AC into lower-voltage DC used by computer components."},
{front:"Which common power-supply form factors are obsolete?",back:"AT and ATX."},
{front:"What is the most common power-supply type?",back:"ATX12V, which adds a dedicated CPU power connector."},
{front:"What is EPS12V used for?",back:"It began in network servers and is now also used in high-end desktops."},
{front:"What are the common PC power-supply voltages?",back:"3.3 V, 5 V, and 12 V."},
{front:"What generally uses 3.3 V and 5 V? What uses 12 V?",back:"Digital circuits use 3.3/5 V; motors in drives and fans commonly use 12 V."},
{front:"What is a power-supply rail?",back:"The internal printed circuit board where external power cables connect; supplies may be single-, dual-, or multi-rail."},
{front:"Why are power connectors keyed?",back:"They are shaped to fit in only the correct orientation."},
{front:"What do Molex and 6/8-pin PCIe power connectors commonly power?",back:"Molex powers drives/devices; 6/8-pin PCIe powers demanding components such as graphics cards."},
{front:"What are two other names for a motherboard?",back:"System board and main board."},
{front:"What are buses on a motherboard?",back:"Electrical pathways on the printed circuit board that connect components."},
{front:"What does the chipset control?",back:"Hardware communication with the CPU/motherboard; it also affects supported memory and connectors."},
{front:"BIOS vs UEFI?",back:"BIOS helps boot and manage hardware; modern systems generally use the newer UEFI."},
{front:"What is firmware?",back:"Programming that allows an operating system to control hardware."},
{front:"What does SATA stand for and connect?",back:"Serial Advanced Technology Attachment; it connects optical drives, HDDs, and SSDs."},
{front:"What is hot swapping?",back:"Replacing a supported device without powering off the computer; SATA supports it."},
{front:"Northbridge vs southbridge?",back:"Northbridge handles high-speed CPU access to RAM/video; southbridge links the CPU to slower devices such as drives, USB, and expansion slots."},
{front:"What does the CPU do?",back:"The Central Processing Unit interprets and executes hardware and software instructions."},
{front:"Who are two common CPU manufacturers?",back:"Intel and AMD."},
{front:"PGA vs LGA?",back:"PGA has pins under the processor. LGA has pins in the motherboard socket."},
{front:"What does ZIF mean?",back:"Zero Insertion Force—the socket mechanism used to install a processor without pressing it in."},
{front:"Passive vs active cooling?",back:"Passive cooling needs no power, such as a heat sink; active cooling needs power, such as a fan."},
{front:"Why must a computer control heat?",back:"Excess heat can slow the system, cause crashes, and damage components."},
{front:"How many bits are in one byte?",back:"8 bits."},
{front:"RAM vs ROM?",back:"RAM is volatile temporary working storage. ROM is nonvolatile and holds important instructions such as booting."},
{front:"Why can adding RAM speed up a computer?",back:"It reduces movement of active data between RAM and the slower storage drive."},
{front:"Which memory is commonly used for CPU cache?",back:"SRAM, because it is faster than regular DRAM."},
{front:"What are the three cache levels?",back:"L1, L2, and L3; L1 is integrated into the CPU."},
{front:"What can erase EPROM?",back:"Strong ultraviolet light."},
{front:"Nonparity, parity, and ECC memory differ how?",back:"Nonparity does not check errors; parity detects errors; ECC detects and corrects certain errors, but not multiple-bit errors."},
{front:"What transfer widths does DIMM support?",back:"32-bit and 64-bit data transfers."},
{front:"What can multi-channel memory improve?",back:"Memory bandwidth when the motherboard and chipset support the channel configuration."},
{front:"What must match when installing an adapter card?",back:"The adapter card connector must match the expansion slot."},
{front:"PCI vs PCIe?",back:"PCI is an older, mostly obsolete 32- or 64-bit bus. PCIe is the modern serial expansion standard."},
{front:"What are common PCIe slot sizes?",back:"x1, x4, x8, and x16."},
{front:"How do mixed PCIe versions operate?",back:"PCIe is backward-compatible; the link runs at the lowest-version component's supported speed."},
{front:"How much slot power can PCIe provide?",back:"Many slots provide up to 25 W; graphics slots may provide up to 75 W, with powerful GPUs needing extra PSU power."},
{front:"What does a riser card do?",back:"It adds additional expansion slots."},
{front:"What adapter cards provide networking?",back:"A NIC provides wired network connectivity; a wireless NIC connects using radio frequencies."},
{front:"HDD vs SSD?",back:"An HDD uses magnetic moving disks. An SSD uses flash memory, has no moving parts, and is faster, quieter, cooler, and more efficient."},
{front:"What do RPM values describe in an HDD?",back:"Disk rotation speed; common values are 5400, 7200, 10,000, and 15,000 RPM."},
{front:"What are common HDD sizes?",back:"3.5-inch desktop, 2.5-inch mobile, and 1.8-inch form factors."},
{front:"What is NVMe?",back:"Non-Volatile Memory Express, designed for efficient SSD communication over PCIe."},
{front:"What is an SSHD?",back:"A Solid State Hybrid Drive combining a magnetic HDD with flash cache."},
{front:"ROM, R, RW/RE on optical media mean what?",back:"ROM is prerecorded/read-only, R is write-once, and RW or Blu-ray RE is rewritable."},
{front:"DVI-D vs DVI-A vs DVI-I?",back:"DVI-D is digital, DVI-A is analog, and DVI-I supports both."},
{front:"Adapter vs converter?",back:"An adapter physically connects technologies; a converter also translates the signal."},
{front:"Which input device is best for secure access?",back:"A biometric device, such as a fingerprint or facial-recognition scanner."},
{front:"Where are barcode scanners commonly used?",back:"Self-checkout counters."},
{front:"LCD vs LED vs OLED?",back:"LCD uses liquid crystals; LED is an LCD with LED backlighting; OLED pixels emit their own light for deeper blacks."},
{front:"VR vs AR?",back:"VR replaces/block surroundings with a simulated 3D environment; AR overlays digital content while the real world remains visible."},
{front:"What does a printer produce and maintain?",back:"Hard copies on paper or as 3D objects; hardware needs maintenance and drivers should stay updated."},
{front:"What tool helps prevent ESD during service?",back:"An antistatic wristband."},
{front:"What are Torx drivers, crimpers, and cable testers used for?",back:"Torx drivers turn Torx screws, crimpers attach connectors, and cable testers verify cables/connections."}
];

const CSIT_QUIZ=CSIT_CARDS.map((card,index)=>({question:card.front,answer:card.back,index}));
